services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security_simple_project_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/security_simple_project_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      # для ADMIN
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: changeMe_123!
      ADMIN_NAME: Admin

      # для USER
      USER_EMAIL: user@example.com
      USER_PASSWORD: user123!
      USER_NAME: User

volumes:
  pgdata: